### ISSUE TITLE
Go back to main page after typing test started

### ISSUE THREAD

**Issue by milan-rabara** [salmannotkhan/typing-test#12]
Hey @salmannotkhan 

I think the one thing I face while using typing test was that I couldn't leave the test environment then after finishing my test I found out that if I press `tab` then it restarts app so that i can leave with testing environment by pressing `tab` but that is an ugly way to leave the test environment.

I think to adding something like button or `X`  icon to leave test environment it would be a good UX improvement.

What do you think about it ?

**Comment by salmannotkhan** [comment]
Typing-test is keyboard centric typing-test. Adding close button will add nothing but distraction.
