### ISSUE TITLE
More wordlists and themes

### ISSUE THREAD

**Issue by salmannotkhan** [salmannotkhan/typing-test#14]
## Hello contributors

This hacktoberfest, Let's add some more themes and wordlists to typing-test to make it more colorful and fun. Don't forget to include screenshots of the themes with your PRs.

Please note that this needs to be good quality contribution. Otherwise PRs won't merged.

**Comment by Bishal091** [comment]
please assign this task to me.

**Comment by salmannotkhan** [comment]
This is open for multiple contributors. So we cannot assign it to anyone. Please submit your PR and I will review and merge it.

**Comment by salmannotkhan** [comment]
Thank you for all the contributions.
