### ISSUE TITLE
Convert to hook

### ISSUE THREAD

**Issue by faustinozanetto** [salmannotkhan/typing-test#2]
**Is your feature request related to a problem? Please describe.**
My feature request is not related to a problem.

**Describe the solution you'd like**
I really like your project! I was wondering if there would be a possibility of converting the project to use hooks and reducer instead of class componentes.

**Describe alternatives you've considered**
I´ve already tryed to convert it but had no luck.

**Comment by salmannotkhan** [comment]
How do you think it can improve the performance or functionality of typing-test?

**Comment by salmannotkhan** [comment]
> In our observation, the performance differences are negligible, though optimization strategies are a bit different.

> In either case we don’t recommend rewriting your existing components unless you have other reasons and don’t mind being an early adopter. 

Quoted from Dan Abramov(from React team) blog
[Reference](https://overreacted.io/how-are-function-components-different-from-classes/)

**Comment by faustinozanetto** [comment]
More than optimization, I think it would improve code legitibilty and it would be much cleanear and easier to understand.

**Comment by salmannotkhan** [comment]
Yes it could be but currently I don't have time for converting components. I'll keep this issue open in case if wants to do it 👍

**Comment by nooobcoder** [comment]
> Yes, it could be but currently I don't have time for converting components. I'll keep this issue open in case if someone wants to do it

I may try doing it, but hey the old pull requests are still open and you are not confined to either merging or closing them. Please let me know it's status so that I can start over converting to functional components if you are interested.

**Comment by salmannotkhan** [comment]
Yes, I know I've busy schedule right now due to studies. I'll definitely merge it after confirming

**Comment by salmannotkhan** [comment]
We can save docker implementation for later when I get time and you can start working functional components

**Comment by salmannotkhan** [comment]
I started learning functional programming. I think now is the time to convert to work on this issue. I'll start the conversion from today only.

**Comment by salmannotkhan** [comment]
Now, typing-test is fully converted to functional-based components. It was possible by using redux for better state management.
