### ISSUE TITLE
Error when typing using sentances mode.

### ISSUE THREAD

**Issue by itstylerrr** [salmannotkhan/typing-test#8]
When you select the sentence mode, it will randomly move you back to somewhere in the first line.

![image](https://user-images.githubusercontent.com/63240641/156626344-b69e00d1-d7e8-4588-ba8e-faceb005450c.png)

**Comment by salmannotkhan** [comment]
I'm well aware of this issue I'll try to fix it as soon as possible

**Comment by itstylerrr** [comment]
sounds good, thanks.
